[package]
name = "lexicon-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# storage
rusqlite = { version = "0.31", features = ["bundled"] }
# sm2 + general
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
chrono = { version = "0.4", features = ["serde"] }
# mdx parsing
flate2 = "1"
regex = "1"
ripemd = "0.2.0"

[dev-dependencies]
tempfile = "3"
